### ISSUE TITLE
Ensure that version IRIs actually resolve

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/OBO-Dashboard#67] opened 2022-05-17 09:13 UTC
Right now, version IRIs are only checked for syntactic correctness.

**Comment by cthoyt** [comment] 2022-05-17 09:25
Duplicate of https://github.com/OBOFoundry/OBO-Dashboard/issues/21 😅

**Comment by cthoyt** [comment] 2022-05-17 09:28
Relevant code: 

https://github.com/OBOFoundry/OBO-Dashboard/blob/06b7dfbe99a37766217b5ecc5dacb4498a964199/util/dashboard/fp_004.py#L38-L67


will fix this myself

**Closed** 2022-05-18 09:06 UTC
